name: Top GitHub Users
on:
  push:
  pull_request:
  schedule:
    - cron: "0 15 * * *"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release:
    name: GitHub Active Users
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: 14.17.0
      - uses: yusukebe/top-github-users-action@master
        env:
          CUSTOM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
